FROM osrf/ros:kilted-desktop

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    vim \
    python3-colcon-common-extensions \
    ros-kilted-xacro \
    ros-kilted-navigation2 \
    nlohmann-json3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

RUN echo "source /opt/ros/kilted/setup.bash" >> /root/.bashrc

CMD ["bash"]
